version: '3.8'
services:
  gigatest:
    image: docker-gigatest_prod
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    container_name: gigatest_c_prod
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - "3000:3000"