version: '3.8'
services:
  gigatest_dev:
    # image: docker-gigatest_dev
    build:
      context: .
      target: dev
    container_name: gigatest_c_dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development