version: '3.8'
services:
  gigatest:
    # image: docker-gigatest_prod
    build:
      context: .
      target: runner
    container_name: gigatest_c_prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production